### PR TITLE
Annotation support added for chart js reports

### PR DESCRIPTION
**Pull request by pandutibil**

### CODE REVIEW

**Comment by vinukumar-vs** [comment]
@panduankani Can you update the package version as well in Package.json file. So that NPM will take the updated version.

Also I would suggest to follow the git commit message format next time.. It is the practice that Sunbird platform follows across all products..

Commit message format
Issue #{JIRA ticket} fix: {commit message}
example: Issue #CQ-446 fix: Chart JS enhancement for reports

ref:https://udacity.github.io/git-styleguide/

**Comment by pandutibil** [comment]
Sure, will do that.

**Comment by pandutibil** [comment]
The current version is 6.0.0. So, can I make it 6.0.1?

**Comment by pandutibil** [comment]
I have updated the version to 6.0.1

**Review by vinukumar-vs — APPROVED** [review]

**Pull request merged**
