### PR TITLE
Annotation support added for the chart js reports

### PR DESCRIPTION
**Pull request by pandutibil**

### CODE REVIEW

**Review by vinukumar-vs — APPROVED** [review]

**Comment by vinukumar-vs** [comment]
@panduankani Can you share the JIRA ticket or story of these changes?

**Comment by pandutibil** [comment]
Here is the link to JIRA ticket
https://project-sunbird.atlassian.net/browse/CQ-648

**Comment by vinukumar-vs** [comment]
@panduankani I have reverted this PR as it was not pointing to the right branch. 

Can you recreate the PR by pointing to 
https://github.com/Sunbird-Ed/sb-dashlets/tree/V14_Migration

@rajeevsathish

**Comment by pandutibil** [comment]
ok

**Comment by pandutibil** [comment]
I raised a new Pull Request
Here is the link to PR
https://github.com/Sunbird-Ed/sb-dashlets/pull/33/files

Thank You

**Pull request merged**
